### ISSUE TITLE
ETA for a new release?

### ISSUE THREAD

**Issue by basiszwo** [DataDog/datadog-cloudfoundry-buildpack#113]
We are using the buildpack in addition to the java buildpack. 

In mid May there was a change for the location of the datadog agent which was picked up lately by the [java buildpack](https://github.com/cloudfoundry/java-buildpack/commit/5254a19c94873854e1e43cb4bc9f5f6fdbfffce7).

The change breaks the usage of the latest java buildpack together with the 4.22.0 version of the datadog cloudfoundry buildpack, as the datadog agent detection fails. 

We already [opened an issue](https://github.com/cloudfoundry/java-buildpack/issues/897) in the java buildpack project. 

As there are 2 solutions to the current issue 

1. rolling back to an older version of the java buildpack or 
2. having a new datadog-cloudfoundry buildpack release 

We were wondering if there's an ETA for a new release that includes [the missing change](https://github.com/DataDog/datadog-cloudfoundry-buildpack/commit/fec40fe9de492beedb7234e586f904841070dc1b) for the java buildpack.

Thank you very much!

**Comment by basiszwo** [comment]
the change in the java buildpack was rolled back. anyway it would be great to know about a new release. any ideas on when a new release will happen?

**Comment by zippolyte** [comment]
Hey @basiszwo, thanks for the report.

I've just published a new release of the buildpack https://github.com/DataDog/datadog-cloudfoundry-buildpack/releases/tag/4.23.0.

**Comment by basiszwo** [comment]
Thank you very much!
