### ISSUE TITLE
Enable Infrastructure Processes 

### ISSUE THREAD

**Issue by stasfilin** [DataDog/datadog-cloudfoundry-buildpack#116]
Hi there,
So I got a problem with enabling Live Process
i tried to use `DD_PROCESS_AGENT_ENABLED: true` - but it's doesn't work

I know that for `datadog.yml` it's possible to use
```
process_config:
    enabled: 'true'
```

But how to correctly turn on this for CF?

Best Regards,
Stanislav

**Comment by zippolyte** [comment]
Hi ! 

The process agent component is not available in the buildpack. To collect process information for your application, you can use the [datadog-agent-boshrelease](https://github.com/DataDog/datadog-agent-boshrelease) combined with the [datadog-cluster-agent-boshrelease](https://github.com/DataDog/datadog-cluster-agent-boshrelease), or directly the [datadog cluster monitoring tile](https://network.pivotal.io/products/datadog/)

**Comment by stasfilin** [comment]
Thanks @zippolyte
