### ISSUE TITLE
New buildpack release based on agent version 7.40.0

### ISSUE THREAD

**Issue by basiszwo** [DataDog/datadog-cloudfoundry-buildpack#138]
Lately the agent got a new release with [version 7.40.0](https://github.com/DataDog/datadog-agent/releases/tag/7.40.0) which is long awaited in my company. 

The new agent version hopefully includes a fix correctly tagging apm traces with the CloudFoundry application instance id.

It would be great to see a new buildpack release which includes agent version 7.40.0

Can I help with anything?

Thank you very much!

**Comment by NouemanKHAL** [comment]
Hi @basiszwo,

We are currently working on a release with [version 7.40.1](https://github.com/DataDog/datadog-agent/releases/tag/7.40.1), it should be available next week.

Hope this helps, let us know if you have any other questions!

**Comment by NouemanKHAL** [comment]
Both buildpack and Pivotal Tile have been released.

- Buildpack: https://github.com/DataDog/datadog-cloudfoundry-buildpack/releases/tag/4.34.0
- Pivotal Tile: https://network.pivotal.io/products/datadog-application-monitoring#/releases/1204860
