### ISSUE TITLE
Tags only set in first entry of LOGS_CONFIG

### ISSUE THREAD

**Issue by Pharb** [DataDog/datadog-cloudfoundry-buildpack#173]
**Describe the bug**

Missing tags in Datadog logs with a config similar to this:

```yaml
LOGS_CONFIG: '[{"type":"file","path":"<PATH_A>","source":"<SOURCE_A>"}, {"type":"file","path":"<PATH_B>","source":"<SOURCE_B>"}]'
DD_TAGS: foo:bar
```

**To Reproduce**
1. Configure CloudFoundry buildpack with `LOGS_CONFIG` specifying multiple log sources and `DD_TAGS`
2. Check logs from both sources on Datadog
3. Notice that only logs from the first source have the tags from `DD_TAGS` (SOURCE_A in the example above), but not the logs from the second source (SOURCE_B).

**Expected behavior**
`DD_TAGS` should apply equally to all sources in `LOGS_CONFIG`.

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
  - buildpack version: [4.36.0](https://github.com/DataDog/datadog-cloudfoundry-buildpack/releases/tag/4.36.0)

**Additional context**
After some debugging with the following environment variables, I noticed the issue in the file `/home/vcap/app/.datadog/dist/conf.d/logs.d/logs.yaml`:
```yaml
        DD_UPDATE_SCRIPT_LOG_LEVEL: DEBUG
        DD_LOG_LEVEL: debug
```
I suspect the problem happens because `tags_list` is only set for the first entry in `logs`:
```ruby
config["logs"][0]["tags"] = tags_list
```
https://github.com/DataDog/datadog-cloudfoundry-buildpack/blob/master/lib/scripts/create_logs_config.rb#L50

**Comment by NouemanKHAL** [comment]
Hi @Pharb,

Thanks for reporting this issue!

I drafted a PR for the issue #175, tested it on our environment and it seems to work as expected.

Could you check that it works for you?

You can follow the steps on this [document](https://github.com/DataDog/datadog-cloudfoundry-buildpack/blob/master/DEVELOPMENT.md#building) to build your own buildpack based on the PR's branch.

Let us know if you have any more questions!
