### ISSUE TITLE
buildpack doesn't have nginx config support

### ISSUE THREAD

**Issue by PXMYH** [DataDog/datadog-cloudfoundry-buildpack#18]
Hi seems like there's no nginx configuration support for the buildpack (currently supported configurations are `cpu.d  docker.d  file_handle.d  go_expvar.d  io.d  jmx.d  kubernetes_apiserver.d  load.d  memory.d  ntp.d  uptime.d`), which can be migrated from https://github.com/DataDog/integrations-core/blob/master/nginx/datadog_checks/nginx/data/conf.yaml.example

Can we add the nginx support?

**Comment by irabinovitch** [comment]
@PXMYH Apologies for the delay in reply here. I am a PM on the Datadog team focused on PCF and other orchestrators.  Would you be available to chat briefly about your monitoring workflows for PCF?

**Comment by irabinovitch** [comment]
@PXMYH Circling back. Do you have availability to connect on this?

**Comment by KamikaZeeFu** [comment]
Hi,
we are also in need of proper nginx support via the datadog buildpack. I already have a ticket open with support.

**Comment by gzussa** [comment]
The agent shipped inside the buildpack does not support integrations. As a workaround, you could emit any metrics via the loggregator (this is also the Pivotal recommended way), and pick them up as app metrics via the firehose. We released a new version of our nozzle that you can try out. Closing this issue.
