### ISSUE TITLE
Configuration of datadog's own logs

### ISSUE THREAD

**Issue by christopherfrieler** [DataDog/datadog-cloudfoundry-buildpack#59]
Hi,

we would like to configure the logs of the datadog-agent itself (not the application-logs it's shipping) to get json logs.

Background: We are using this buildpack within PCF to collect the application-logs **in json-format** from standard-out. In addition we get the logs of the datadog-agent itself, which are not structured, not tagged and so are hard to filter out when searching in the logs.

In the lib/dist/datadog.yaml I've found the property `log_format_json`. I would like to be able to set it to `yes`. Or does it have any impact that I don't see yet and is set to `no` for a good reason?

**Comment by zippolyte** [comment]
Hi @christopherfrieler,

I don't see a problem configuring the agent to format its logs to JSON. You can do so by setting the environment variable `DD_LOG_FORMAT_JSON` to `true` in your app.

It would also probably be possible for us to implement the possibility to exclude agent logs from the stdout that is redirected to the logs agent, if that would be a better option.

**Comment by christopherfrieler** [comment]
Hi @zippolyte,

thanks for the fast response.

Formatting the logs as json will be totally sufficient. I just didn't know about this env-variable. 

Seems like this is possible for all options: [https://github.com/DataDog/datadog-agent/blob/master/docs/agent/config.md#environment-variables](https://github.com/DataDog/datadog-agent/blob/master/docs/agent/config.md#environment-variables). Maybe this could be mentioned in the README of the buildpack?

**Comment by zippolyte** [comment]
Indeed, thanks for adding this bit to the README 😃 
Closing this issue then
