### ISSUE TITLE
META-buildpack is deprecated

### ISSUE THREAD

**Issue by cy4n** [DataDog/datadog-cloudfoundry-buildpack#62]
https://github.com/cf-platform-eng/meta-buildpack

NOTE: Meta-buildback is being **deprecated**
Changes to the core CloudFoundry lifecycle process are making it hard to guarantee on-going compatibility with meta-buildpack and decorators. Some of the use cases for decorators can now be solved by leveraging **the new supply buildpack functionality**. Some examples can be found at the bottom of this page.

**Comment by zippolyte** [comment]
Hey @cy4n, 

Thanks for the notice. We should already be supporting the supply functionality, as we do have a supply script: https://github.com/DataDog/datadog-cloudfoundry-buildpack/blob/master/bin/supply.

**Comment by gzussa** [comment]
As per @zippolyte comment i am closing this PR.
